name: polecat
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.74
  - pip=19.3.1
  - snakemake-minimal=5.13
  - libpysal=4.3.0
  - nodejs=10.12.0
  - openjdk
  - cov-ert::jclusterfunk
  - pip:
    - git+https://github.com/cov-ert/datafunk.git
    - git+https://github.com/cov-ert/reportfunk.git
    - git+https://github.com/cov-ert/clusterfunk.git
    - git+https://github.com/COG-UK/civet.git

